### ISSUE TITLE
can't create (initialize) new projects

### ISSUE THREAD

**Issue by PJVervoorn** [WallaceWilliam/framework-esp8266-rtos-sdk-idf-platformio#9]
I get the error below when I try to create a new project.
It looks like there are is no default_config.
I have tried it on my current PIO instance and on a new (blank) one.
And, tried for a few different boards.
Am I missing something obvious, can I help you getting this to work?

PIO Core Call Error: "The current working directory P:\\Poof will be used for the project.\r\n\r\nThe next files/directories have been created in P:\\Poof\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing nodemcuv2 (platform: custom8266; board: nodemcuv2; framework: esp8266-rtos-sdk)\r\n--------------------------------------------------------------------------------\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/custom8266/nodemcuv2.html\r\nPLATFORM: custom Espressif 8266 1.1.0 > NodeMCU 1.0 (ESP-12E Module)\r\nHARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash\r\nPACKAGES: \r\n - framework-esp8266-rtos-sdk 1f5bed1 \r\n - tool-cmake 3.16.4 \r\n - tool-mconf 1.4060000.20190628 (406.0.0) \r\n - tool-ninja 1.9.0 \r\n - toolchain-xtensa-lx106-elf 5.2.0+100\r\nReading CMake configuration...\r\nKeyError: 'compileGroups':\r\n File \"C:\\Users\\Peter\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\main.py\", line 168:\r\n env.SConscript(\"$BUILD_SCRIPT\")\r\n File \"C:\\Users\\Peter\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 597:\r\n return _SConscript(self.fs, *files, **subst_kw)\r\n File \"C:\\Users\\Peter\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 286:\r\n exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\r\n File \"C:\\Users\\Peter\\.platformio\\platforms\\custom8266\\builder\\main.py\", line 241:\r\n target_elf = env.BuildProgram()\r\n File \"C:\\Users\\Peter\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 219:\r\n return self.method(*nargs, **kwargs)\r\n File \"C:\\Users\\Peter\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 61:\r\n env.ProcessProgramDeps()\r\n File \"C:\\Users\\Peter\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 219:\r\n return self.method(*nargs, **kwargs)\r\n File \"C:\\Users\\Peter\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 118:\r\n env.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\r\n File \"C:\\Users\\Peter\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 219:\r\n return self.method(*nargs, **kwargs)\r\n File \"C:\\Users\\Peter\\.platformio\\penv\\Lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 330:\r\n SConscript(env.GetFrameworkScript(f), exports=\"env\")\r\n File \"C:\\Users\\Peter\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 660:\r\n return method(*args, **kw)\r\n File \"C:\\Users\\Peter\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 597:\r\n return _SConscript(self.fs, *files, **subst_kw)\r\n File \"C:\\Users\\Peter\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 286:\r\n exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\r\n File \"C:\\Users\\Peter\\.platformio\\platforms\\custom8266\\builder\\frameworks\\esp8266-rtos-sdk.py\", line 1009:\r\n project_flags = get_app_flags(project_config, default_config)\r\n File \"C:\\Users\\Peter\\.platformio\\platforms\\custom8266\\builder\\frameworks\\esp8266-rtos-sdk.py\", line 390:\r\n default_flags = _extract_flags(default_config)\r\n File \"C:\\Users\\Peter\\.platformio\\platforms\\custom8266\\builder\\frameworks\\esp8266-rtos-sdk.py\", line 377:\r\n for cg in config[\"compileGroups\"]:\r\n========================= [FAILED] Took 25.94 seconds ========================="

**Comment by WallaceWilliam** [comment]
please, reinstall

**Comment by PJVervoorn** [comment]
Great, that solved it.
Now new projects are succesfully created.
New issue coming up :)
